#!/usr/bin/env bash
# Family personas updater

set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PERSONAS=(
  "parker:parker:8021:parker.hoth.home"
  "ramona:ramona:8022:ramona.hoth.home"
  "sarah:sarah:8023:sarah.hoth.home"
  "greg:greg:8024:greg.hoth.home"
)

NGINX_CONF_LOCAL="$BASE_DIR/nginx.family.conf"
NGINX_CONF_TARGET="/etc/nginx/sites-available/family-dashboard"
NGINX_SITE_LINK="/etc/nginx/sites-enabled/family-dashboard"

ACTION="${1:-update}"
APPLY_NGINX="${APPLY_NGINX:-0}"
OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"
OLLAMA_MODEL="${OLLAMA_MODEL:-qwen3:1.7b}"

[[ "$ACTION" == "--nginx" ]] && { ACTION="update"; APPLY_NGINX=1; }

log() { printf "[%s] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }

ensure_repo() {
  local name="$1" branch="$2"
  local repopath="$BASE_DIR/$name"
  [[ ! -d "$repopath/.git" ]] && { log "[ERROR] Repo for $name not found at $repopath"; return 1; }
  [[ -n "$(git -C "$repopath" status --porcelain)" ]] && { log "[WARN] $name has local changes; skipping"; return 1; }
  git -C "$repopath" fetch --all --prune
  git -C "$repopath" checkout "$branch"
  git -C "$repopath" merge --ff-only "origin/$branch" || { log "[ERROR] Failed to fast-forward $name"; return 1; }
  git -C "$repopath" merge --no-edit origin/master || { log "[ERROR] Merge master failed for $name"; return 1; }
  log "[OK] $name updated from origin/master"
}

setup_venv() {
  local venvpath="$1/.venv"
  local reqfile="$1/requirements.txt"
  if [[ ! -d "$venvpath" ]]; then
    log "Creating venv in $venvpath"
    python3 -m venv "$venvpath"
  fi
  source "$venvpath/bin/activate"
  pip install --upgrade pip -q
  pip install -r "$reqfile" -q
  deactivate
}

set_ollama_provider() {
  local dbfile="$1/dashboard.db"
  [[ ! -f "$dbfile" ]] && { log "[WARN] No database for $(basename "$1"), skipping Ollama"; return 0; }
  sqlite3 "$dbfile" "UPDATE ai_providers SET config_data = '{\"base_url\": \"$OLLAMA_URL\", \"model_name\": \"$OLLAMA_MODEL\", \"is_active\": true, \"is_default\": true}' WHERE id = 1;" || { log "[ERROR] Ollama update failed"; return 1; }
  log "[OK] Ollama set to $OLLAMA_MODEL for $(basename "$1")"
}

restart_uvicorn() {
  local name="$1" port="$2"
  local repopath="$BASE_DIR/$name"
  local venvpath="$repopath/.venv"
  local pidfile="$repopath/dashboard.pid"
  local logfile="$repopath/dashboard.log"
  if [[ -f "$pidfile" ]]; then
    local oldpid; oldpid=$(cat "$pidfile")
    ps -p "$oldpid" >/dev/null 2>&1 && { log "Stopping $name (pid $oldpid)"; kill "$oldpid" || true; sleep 2; }
  fi
  lsof -ti:"$port" 2>/dev/null | xargs -r kill -9 || true
  log "Starting $name on port $port"
  (cd "$repopath" && nohup "$venvpath/bin/python" -m uvicorn src.main:app --host 0.0.0.0 --port "$port" --log-level info > "$logfile" 2>&1 & echo $! > "$pidfile")
  log "[OK] $name running (pid $(cat "$pidfile"))"
}

write_nginx_conf() {
  log "Writing nginx config to $NGINX_CONF_LOCAL"
  cat > "$NGINX_CONF_LOCAL" <<'EOF'
# Generated by update_family.sh
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
EOF
  for entry in "${PERSONAS[@]}"; do
    IFS=":" read -r pname pbranch pport pdomain <<<"$entry"
    cat >> "$NGINX_CONF_LOCAL" <<EOF
server {
    listen 80;
    server_name $pdomain;
    location / {
        proxy_pass http://127.0.0.1:$pport;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
  done
}

install_nginx_conf() {
  write_nginx_conf
  [[ $APPLY_NGINX -eq 0 && "$ACTION" != "nginx" ]] && { log "Nginx config ready locally. Use APPLY_NGINX=1 to install."; return 0; }
  [[ $EUID -ne 0 ]] && { log "Applying nginx requires sudo..."; sudo true; }
  sudo cp "$NGINX_CONF_LOCAL" "$NGINX_CONF_TARGET"
  sudo ln -sf "$NGINX_CONF_TARGET" "$NGINX_SITE_LINK"
  sudo nginx -t && sudo systemctl reload nginx
  log "[OK] Nginx reloaded"
}

status() {
  log "Persona status:"
  for entry in "${PERSONAS[@]}"; do
    IFS=":" read -r pname pbranch pport pdomain <<<"$entry"
    local pidfile="$BASE_DIR/$pname/dashboard.pid"
    if [[ -f "$pidfile" ]] && ps -p "$(cat "$pidfile")" >/dev/null 2>&1; then
      log "- $pname on $pdomain:$pport (pid $(cat "$pidfile"))"
    else
      log "- $pname on $pdomain:$pport NOT RUNNING"
    fi
  done
}

case "$ACTION" in
  update)
    for entry in "${PERSONAS[@]}"; do
      IFS=":" read -r pname pbranch pport pdomain <<<"$entry"
      log "--- $pname ($pbranch) ---"
      ensure_repo "$pname" "$pbranch" || continue
      setup_venv "$BASE_DIR/$pname"
      set_ollama_provider "$BASE_DIR/$pname"
      restart_uvicorn "$pname" "$pport"
    done
    install_nginx_conf
    ;;
  nginx) install_nginx_conf ;;
  status) status ;;
  *) echo "Usage: $0 [update|nginx|status]" >&2; exit 1 ;;
esac
