#!/usr/bin/env bash
# Family personas updater: fetch latest master, merge into persona branches, install deps, restart uvicorn per persona, and optionally refresh nginx config.

set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Persona entries: name:branch:port:domain
PERSONAS=(
  "parker:parker:8021:parker.hoth.home"
  "ramona:ramona:8022:ramona.hoth.home"
  "sarah:sarah:8023:sarah.hoth.home"
  "greg:greg:8024:greg.hoth.home"
)

NGINX_CONF_LOCAL="$BASE_DIR/nginx.family.conf"
NGINX_CONF_TARGET="/etc/nginx/sites-available/family-dashboard"
NGINX_SITE_LINK="/etc/nginx/sites-enabled/family-dashboard"

ACTION="${1:-update}"          # update (default) | nginx | full | status
APPLY_NGINX="${APPLY_NGINX:-0}" # set to 1 or pass --nginx to push config + reload
OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"
OLLAMA_MODEL="${OLLAMA_MODEL:-qwen3:1.7b}"

if [[ "$ACTION" == "--nginx" ]]; then
  ACTION="update"
  APPLY_NGINX=1
fi

log() { printf "[%s] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }

ensure_repo() {
  local name="$1" branch="$2" path="$BASE_DIR/$1"
  if [[ ! -d "$path/.git" ]]; then
    log "[ERROR] Repo for $name not found at $path" && return 1
  fi
  if [[ -n "$(git -C "$path" status --porcelain)" ]]; then
    log "[WARN] $name has local changes; skipping to avoid overwriting"
    return 1
  fi
  git -C "$path" fetch --all --prune
  git -C "$path" checkout "$branch"
  git -C "$path" merge --ff-only "origin/$branch" || {
    log "[ERROR] Failed to fast-forward $name ($branch); resolve manually"; return 1; }
  if ! git -C "$path" merge --no-edit origin/master; then
    log "[ERROR] Merge master -> $branch failed for $name; fix conflicts and rerun"; return 1
  fi
  log "[OK] $name updated from origin/master"
}

setup_venv() {
  local path="$1" venv="$path/.venv"
  if [[ ! -d "$venv" ]]; then
    log "Creating venv in $path/.venv"
    python3 -m venv "$venv"
  fi
  source "$venv/bin/activate"
  python -m pip install --upgrade pip
  python -m pip install -r "$path/requirements.txt"
  deactivate
}

set_ollama_provider() {
  local path="$1" db="$path/dashboard.db"
  if [[ ! -f "$db" ]]; then
    log "[WARN] No database found for $(basename "$path"), skipping Ollama default"
    return 0
  fi
  sqlite3 "$db" "UPDATE ai_providers SET config_data = '{\"base_url\": \"$OLLAMA_URL\", \"model_name\": \"$OLLAMA_MODEL\", \"is_active\": true, \"is_default\": true}' WHERE id = 1;" || {
    log "[ERROR] Failed to set Ollama default for $(basename "$path")"; return 1; }
  log "[OK] Ollama default set to $OLLAMA_MODEL at $OLLAMA_URL for $(basename "$path")"
}

restart_uvicorn() {
  local name="$1" port="$2" path="$BASE_DIR/$1" venv="$path/.venv" pidfile="$path/dashboard.pid" logfile="$path/dashboard.log"
  if [[ -f "$pidfile" ]]; then
    local pid
    pid=$(cat "$pidfile")
    if ps -p "$pid" >/dev/null 2>&1; then
      log "Stopping $name (pid $pid)"
      kill "$pid" || true
      sleep 2
    fi
  fi
  if command -v lsof >/dev/null 2>&1; then
    lsof -ti:"$port" 2>/dev/null | xargs -r kill -9 || true
  fi
    log "Starting $name on port $port"
  (cd "$path" && nohup "$venv/bin/python" -m uvicorn src.main:app --host 0.0.0.0 --port "$port" --log-level info > "$logfile" 2>&1 & echo $! > "$pidfile")
  log "[OK] $name running (pid $(cat "$pidfile")) log=$logfile"
}

write_nginx_conf() {
  log "Writing nginx config to $NGINX_CONF_LOCAL"
  cat > "$NGINX_CONF_LOCAL" <<'EOF'
# Generated by family/update_family.sh
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
EOF
  for entry in "${PERSONAS[@]}"; do
    IFS=":" read -r name branch port domain <<<"$entry"
    cat >> "$NGINX_CONF_LOCAL" <<EOF
server {
    listen 80;
    server_name $domain;

    location / {
        proxy_pass http://127.0.0.1:$port;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
  done
}

install_nginx_conf() {
  write_nginx_conf
  if [[ $APPLY_NGINX -eq 0 && "$ACTION" != "nginx" ]]; then
    log "Nginx config written locally. Set APPLY_NGINX=1 or run with --nginx to install + reload."
    return 0
  fi
  if [[ $EUID -ne 0 ]]; then
    log "Applying nginx config requires sudo. Prompting..."
    sudo true
  fi
  sudo cp "$NGINX_CONF_LOCAL" "$NGINX_CONF_TARGET"
  sudo ln -sf "$NGINX_CONF_TARGET" "$NGINX_SITE_LINK"
  sudo nginx -t
  sudo systemctl reload nginx
  log "[OK] Nginx reloaded with $NGINX_CONF_TARGET"
}

status() {
  log "Persona status:"
  for entry in "${PERSONAS[@]}"; do
    IFS=":" read -r name branch port domain <<<"$entry"
    local pidfile="$BASE_DIR/$name/dashboard.pid"
    if [[ -f "$pidfile" ]] && ps -p "$(cat "$pidfile")" >/dev/null 2>&1; then
      log "- $name on $domain:$port (pid $(cat "$pidfile"))"
    else
      log "- $name on $domain:$port is not running"
    fi
  done
}

case "$ACTION" in
  update)
    for entry in "${PERSONAS[@]}"; do
      IFS=":" read -r name branch port domain <<<"$entry"
      log "--- $name (${branch}) ---"
      ensure_repo "$name" "$branch" || continue
      setup_venv "$BASE_DIR/$name"
      set_ollama_provider "$BASE_DIR/$name"
      restart_uvicorn "$name" "$port"
    done
    if [[ $APPLY_NGINX -eq 1 ]]; then
      install_nginx_conf
    else
      write_nginx_conf
      log "Nginx config ready at $NGINX_CONF_LOCAL"
    fi
    ;;
  nginx)
    install_nginx_conf
    ;;
  full)
    ACTION=update
    APPLY_NGINX=1
    "$0" update
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 [update|nginx|full|status] [--nginx]" >&2
    exit 1
    ;;
 esac
